### ISSUE TITLE
推特名字消失了。。

### ISSUE THREAD

**Issue by wudifeixue** [cn-matsuri/matsuri_translation#13]
不知道为什么，非常神奇，在增加时间后，推特用户名失踪了。。
实在是不理解，需要调查修复

![XFA0({U6QNWO457KP%ZSLBS](https://user-images.githubusercontent.com/7316929/60881720-7dc25480-a203-11e9-99f0-a2b7fffa7e0a.jpg)

**Comment by fzxiao233** [comment]
更换服务器实例后解决
