### ISSUE TITLE
后端目前遇见的问题

### ISSUE THREAD

**Issue by wudifeixue** [cn-matsuri/matsuri_translation#4]
现在后端测试给出的界面是这样

![2019-07-07-21_31_31](https://user-images.githubusercontent.com/7316929/60774103-5cab1800-a0cc-11e9-86fd-5e7056ccf684.png)

有几个地方希望改进一下，而且主要是我不太明白你怎么设计的，自己做不了。

- Unicode表情会炸掉程序，这个很严重，需要改进。
- 传送回来的图片过大，很多不需要的背景可以直接裁减掉。
- 希望可以用mobile站的链接，而不只是主站，原因是订阅按钮在主站显示出来，效果很不好看。

**Comment by wudifeixue** [comment]
![image](https://user-images.githubusercontent.com/7316929/60775720-465c8680-a0e3-11e9-9453-b95d814191af.png)
鱼的unicode表情会这样

**Comment by fzxiao233** [comment]
> ![image](https://user-images.githubusercontent.com/7316929/60775720-465c8680-a0e3-11e9-9453-b95d814191af.png)
> 鱼的unicode表情会这样
这是因为服务器上缺少字库导致的

**Comment by fzxiao233** [comment]
问题已规整至project
