### ISSUE TITLE
订阅按钮显示出来不好看，让界面变得更美观

### ISSUE THREAD

**Issue by fzxiao233** [cn-matsuri/matsuri_translation#6]

**Comment by fzxiao233** [comment]
这样我又得重写jq，先搁置一下

**Comment by wudifeixue** [comment]
其实有了新的想法，对不好看的地方直接用js修改页面就行了，自从昨天改完时间后大概知道咋做了

**Comment by wudifeixue** [comment]
这个处理起来很简单，就是写好如何删掉或者隐藏掉页面js的代码，处理成理想状态，然后一股脑按照同样格式在这里加进去
https://github.com/cn-matsuri/matsuri_translation/blob/2914a771493b91033d00ae7baecd50348272823c/Matsuri_translation/tweet_process.py#L33

**Comment by fzxiao233** [comment]
其实我觉得可以在按钮的这个位置放上例如powered by 烤推机（你们先取个名字）之类的东西？

**Comment by wudifeixue** [comment]
额，这样岂不是别人要蛋疼了？..不太好吧，除非能很微妙的标记

**Comment by wudifeixue** [comment]
已经完成
