### ISSUE TITLE
时间显示有误

### ISSUE THREAD

**Issue by fzxiao233** [cn-matsuri/matsuri_translation#8]

**Comment by wudifeixue** [comment]
好像在我改了服务器时间后，这个有变化

**Comment by wudifeixue** [comment]
在原文推中找到了时间戳特性
<span class="_timestamp js-short-timestamp js-relative-timestamp" data-time="1562582490" data-time-ms="1562582490000" data-long-form="true" aria-hidden="true">21h</span>

data-time-ms在多处出现，不过可以完美转换成本地时间。

选中目标时间区域`document.querySelector('.client-and-actions .metadata > span').innerText = '新的时间结果'`
